services:
  - type: web
    name: ai-resume-analyzer
    env: node
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_uri
      - key: NODE_ENV
        value: production
